name: Python Script Workflow

on:
  pull_request:
    branches:
      - master # Adjust this branch name to your needs

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 # Specify the Python version you need (e.g., 3.6, 3.7, 3.8)

      - name: Run Python script
        run: python main.py # Replace with the actual command to run your Python script

